/**
 * THE message contract. Single source of truth for every frame that crosses
 * a WebSocket in this repo. Schemas are zod; TS types are inferred from them.
 *
 * Read docs/CONTRACT.md before changing anything here. Changes must be
 * announced to the whole team (they break all three apps at once).
 */
import { z } from 'zod';

export const PROTOCOL_VERSION = 1;

// ---------- primitives ----------

/** 4 uppercase letters, no I/O (ambiguous on screen). */
export const JoinCode = z.string().regex(/^[A-HJ-NP-Z]{4}$/);
export type JoinCode = z.infer<typeof JoinCode>;

/** Stable per-phone id, generated by the controller once and kept in localStorage. */
export const PlayerId = z.string().min(8).max(64);
export type PlayerId = z.infer<typeof PlayerId>;

export const PlayerName = z.string().trim().min(1).max(16);
export type PlayerName = z.infer<typeof PlayerName>;

/** Analog stick. x right, y DOWN (screen coordinates). Magnitude <= 1. */
export const Axis = z.object({
  x: z.number().min(-1).max(1),
  y: z.number().min(-1).max(1),
});
export type Axis = z.infer<typeof Axis>;

/** Generic buttons. Add here (and nowhere else) if a game needs more. */
export const Buttons = z.object({
  a: z.boolean(),
  b: z.boolean(),
});
export type Buttons = z.infer<typeof Buttons>;
export type ButtonId = keyof Buttons;

/** The complete controller state. Sent whole every time (no deltas). */
export const InputState = z.object({
  axis: Axis,
  buttons: Buttons,
});
export type InputState = z.infer<typeof InputState>;

export const ZERO_INPUT: InputState = Object.freeze({
  axis: { x: 0, y: 0 },
  buttons: { a: false, b: false },
}) as InputState;

/**
 * The only thing a host may push to a phone: small generic hints.
 * Controllers never render the world; this is colour, a short label, a buzz.
 */
export const PlayerUi = z.object({
  color: z.string().max(32).optional(),
  text: z.string().max(40).optional(),
  vibrate: z.number().int().min(0).max(1000).optional(),
});
export type PlayerUi = z.infer<typeof PlayerUi>;

export const Player = z.object({
  id: PlayerId,
  name: PlayerName,
  /** Assigned by the server from a fixed palette, in join order. */
  color: z.string(),
  /** False while the phone is asleep / offline. Identity is kept. */
  connected: z.boolean(),
});
export type Player = z.infer<typeof Player>;

export const JoinErrorReason = z.enum(['room_not_found', 'name_taken', 'room_full', 'invalid']);
export type JoinErrorReason = z.infer<typeof JoinErrorReason>;

// ---------- controller -> server ----------

export const ControllerToServer = z.discriminatedUnion('type', [
  /** Sent on every (re)connect. Same playerId => same identity. */
  z.object({ type: z.literal('join'), code: JoinCode, playerId: PlayerId, name: PlayerName }),
  z.object({ type: z.literal('input'), input: InputState }),
  z.object({ type: z.literal('leave') }),
]);
export type ControllerToServer = z.infer<typeof ControllerToServer>;

// ---------- host -> server ----------

export const HostToServer = z.discriminatedUnion('type', [
  /** Pass `code` to reclaim a room after a host reload. */
  z.object({ type: z.literal('create_room'), code: JoinCode.optional() }),
  z.object({ type: z.literal('to_player'), playerId: PlayerId, ui: PlayerUi }),
  z.object({ type: z.literal('to_all'), ui: PlayerUi }),
  z.object({ type: z.literal('kick'), playerId: PlayerId }),
]);
export type HostToServer = z.infer<typeof HostToServer>;

/** What the server accepts as a first frame; the first frame decides the role. */
export const ClientToServer = z.union([ControllerToServer, HostToServer]);
export type ClientToServer = z.infer<typeof ClientToServer>;

// ---------- server -> controller ----------

export const ServerToController = z.discriminatedUnion('type', [
  z.object({ type: z.literal('joined'), code: JoinCode, player: Player }),
  z.object({ type: z.literal('join_error'), reason: JoinErrorReason }),
  z.object({ type: z.literal('ui'), ui: PlayerUi }),
  z.object({ type: z.literal('kicked') }),
  z.object({ type: z.literal('room_closed') }),
  z.object({ type: z.literal('error'), message: z.string() }),
]);
export type ServerToController = z.infer<typeof ServerToController>;

// ---------- server -> host ----------

export const ServerToHost = z.discriminatedUnion('type', [
  /** `players` is non-empty when a room was reclaimed. */
  z.object({ type: z.literal('room_created'), code: JoinCode, players: z.array(Player) }),
  z.object({ type: z.literal('player_joined'), player: Player }),
  z.object({ type: z.literal('player_reconnected'), playerId: PlayerId }),
  z.object({ type: z.literal('player_disconnected'), playerId: PlayerId }),
  /** Player removed for good (kicked or left). */
  z.object({ type: z.literal('player_left'), playerId: PlayerId }),
  /** `t` = server receive time, ms since epoch. */
  z.object({ type: z.literal('input'), playerId: PlayerId, input: InputState, t: z.number() }),
  z.object({ type: z.literal('error'), message: z.string() }),
]);
export type ServerToHost = z.infer<typeof ServerToHost>;

// ---------- helpers ----------

/** Parse a raw frame (string or already-parsed JSON) against a schema. Returns undefined on failure. */
export function parseFrame<T>(schema: z.ZodType<T>, raw: unknown): T | undefined {
  let data: unknown = raw;
  if (typeof raw === 'string') {
    try {
      data = JSON.parse(raw);
    } catch {
      return undefined;
    }
  }
  const r = schema.safeParse(data);
  return r.success ? r.data : undefined;
}

const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
export function generateJoinCode(): JoinCode {
  let s = '';
  for (let i = 0; i < 4; i++) s += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
  return s;
}

/** Fixed palette, assigned by the server in join order (wraps). */
export const PLAYER_COLORS = [
  '#ef4444', '#3b82f6', '#22c55e', '#eab308', '#a855f7', '#f97316', '#06b6d4', '#ec4899',
  '#84cc16', '#14b8a6', '#f43f5e', '#8b5cf6',
] as const;

export const LIMITS = {
  maxPlayersPerRoom: 32,
  /** Controllers should not send faster than this. */
  inputHz: 30,
  /** Server keeps a host-less room this long for reclaim before closing it. */
  hostReclaimMs: 60_000,
} as const;
